version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi-app
    env_file: .env
    networks:
      - strapi-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: strapi-db
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - strapi-network

  nginx:
    image: nginx:alpine
    container_name: strapi-nginx
    ports:
      - "80:80"  # Nginx exposes Strapi on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - strapi
    networks:
      - strapi-network

networks:
  strapi-network:
    driver: bridge
