name: Deploy Strapi on EC2 using Terraform

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_DIR: terraform/
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read image tag
        id: read_tag  
        working-directory: .
        run: |
          IMAGE_TAG=$(cat dockertag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV 
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      
      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init
 
      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        run: terraform plan -var="image_tag=$IMAGE_TAG"
 
      - name: Terraform Apply
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve -var="image_tag=$IMAGE_TAG"