name: Deploy Strapi on EC2 using Terraform

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_DIR: terraform
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout latest main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Read image tag
        id: read_tag  
        working-directory: .
        run: |
          IMAGE_TAG=$(cat dockertag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV 
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

         
      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: |
           pwd
           ls -al
           terraform init
 
      - name: Terraform Apply
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve -var="image_tag=${{ env.IMAGE_TAG }}"