name: Deploy Strapi on EC2 using Terraform

on:
  workflow_dispatch:        # Allow manual trigger from GitHub UI
  push:
    branches:
      - nagaraj             # Trigger when pushing to nagaraj branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image_tag

      - name: Read image tag
        id: get_tag
        run: echo "tag=$(cat image_tag.txt)" >> $GITHUB_OUTPUT

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan \
          -var="image_tag=${{ steps.get_tag.outputs.tag }}" \
          -var="docker_username=${{ secrets.DOCKER_USERNAME }}" \
          -var="docker_password=${{ secrets.DOCKER_PASSWORD }}" \
          -var="ami=${{ secrets.AMI_ID }}" \
          -var="subnet_id=${{ secrets.SUBNET_ID }}" \
          -var="security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
          -var="key_name=${{ secrets.KEY_NAME }}"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var="image_tag=${{ steps.get_tag.outputs.tag }}" \
          -var="docker_username=${{ secrets.DOCKER_USERNAME }}" \
          -var="docker_password=${{ secrets.DOCKER_PASSWORD }}" \
          -var="ami=${{ secrets.AMI_ID }}" \
          -var="subnet_id=${{ secrets.SUBNET_ID }}" \
          -var="security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
          -var="key_name=${{ secrets.KEY_NAME }}"
        working-directory: terraform
