name: CD - Terraform Deploy

on:
  push:
    branches:
      - nagaraj
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_DIR: my-strapi-app/terraform
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image_tag
          path: .

      - name: Read image tag
        id: read_tag
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        run: terraform plan -var="image_tag=${{ env.IMAGE_TAG }}"

      - name: Terraform Apply
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve -var="image_tag=${{ env.IMAGE_TAG }}"

      - name: Show Strapi Admin URL
        working-directory: ${{ env.TF_DIR }}
        run: |
          echo "Strapi Admin URL:"
          terraform output strapi_address
